
version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: taskmanager_db
    environment:
      POSTGRES_USER: yash
      POSTGRES_PASSWORD: yash123
      POSTGRES_DB: taskmanager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
